---
title: '001831'  
description: '<small>&#8249; [All error codes](/errors/codes#direct-debit)</small>'
---
  
<table>
    <tbody>
        <tr>
            <th class="header"><strong>Error message</strong></th>
            <td class="table-content">Contact the user</td>
        </tr>
        <tr>
            <th class="header"><strong>Description</strong></th>
            <td class="table-content">The pay-in failed for an unknown reason. The end user should be contacted.</td>
        </tr>
        <tr>
            <th class="header"><strong>Categories</strong></th>
            <td class="table-content">  
<div class="label">Mandate</div>  
<div class="label">Direct debit</div>
</td>
        </tr>
    </tbody>
</table>  

#### Example  

This error is returned upon making a Create a Direct Direct-Debit PayIn request.  
```json API Response
{
    "Id":"3333624441",
    "CreationDate":1677717185,
    "AuthorId":"460544459",
    "CreditedUserId":"460544459",
    "Status":"FAILED",
    "ExecutionDate":null,
    "ChargeDate":1678147200,
    "Type":"PAYIN",
    "Nature":"REGULAR",
    "CreditedWalletId":"2744437637",
    "DebitedWalletId":null,
    "CreditedFunds":{
        "Currency":"EUR",
        "Amount":10599
    },
    "DebitedFunds":{
        "Currency":"EUR",
        "Amount":10599
    },
    "Fees":{
        "Currency":"EUR",
        "Amount":0
    },
    "ResultCode":"001831",
    "ResultMessage":"Contact the user",
    "PaymentType":"DIRECT_DEBIT",
    "ExecutionType":"DIRECT",
    "Tag":null,
    "MandateId":"279944444",
    "StatementDescriptor":"Nov2021"
```